# Generated by Django 5.2.7 on 2026-01-20 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='code',
            field=models.CharField(default=uuid.uuid4, help_text='Identificador interno (ex: FIRST_MISSION)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
