# Generated by Django 5.2.7 on 2026-01-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_name_achievement_required_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
