# Generated by Django 5.2.7 on 2026-01-22 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gotchi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mission_type', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='daily', max_length=10)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('tecnica_pontuacao', models.PositiveIntegerField(default=0)),
                ('lideranca_pontuacao', models.PositiveIntegerField(default=0)),
                ('criatividade_pontuacao', models.PositiveIntegerField(default=0)),
                ('disciplina_pontuacao', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('gotchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gotchi.gotchi')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
