# Generated by Django 5.2.7 on 2026-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='criatividade_pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='disciplina_pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='lideranca_pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mission',
            name='tecnica_pontuacao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
