# Generated by Django 5.2.7 on 2026-01-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_missionprogress_gotchi_alter_missionprogress_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='missions_criadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
